portal/portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
    #path("accounts/", include("accounts.urls")),
    #path("accounts/", include("allauth.urls")),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('simpleapp.urls')),

    #path('multiply/', multiply),
]

portal/simpleapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models import Sum

class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.IntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat*3 + cRat
        self.save()

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = [
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    ]

    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)

    name = models.CharField(max_length=50, unique=True)
    description = models.TextField()
    createDate = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='posts')
    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

    def __str__(self):
        return f'{self.name.title()}: {self.description[:20]}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name.title()

class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete = models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete = models.CASCADE)
    pass

class Comment(models.Model):
    postComment = models.ForeignKey(Post, on_delete=models.CASCADE)
    userComment = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    commentTime = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

portal/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<h1>{{ post.name|tsenzor }}</h1>
<h2>{{ post.description|tsenzor }}</h2>
<h3>{{ post.createDate }}</h3>
{% endblock content %}

portal/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

portal/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1> Статья </h1>
<hr>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content%}


portal/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% load custom_tags %}

{% block title %}
Post
{% endblock title %}

{% block content %}
   <h1>Все посты</h1>

   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

{% if perms.simpleapp.add_post %}
    <<a href="{% url 'news_create' %}">Создать новость</a>
        {% endif %}

{% if perms.simpleapp.add_post %}
    <<a href="{% url 'article_create' %}">Создать статью</a>
    {% endif %}



{% if not is_author %}
<button>
    <a class="nav-link" href="{% url 'account_upgrade' %}">
        <h4><strong>Join the authors!</strong></h4>
    </a>
</button>
{% endif %}



   {% if posts %}
       <table>
           <tr>
               <td>Название</td>
               <td>Дата создания</td>
               <td>Описание</td>
               <td>Категория</td>
               {% if perms.simpleapp.change_post or perms.simpleapp.delete_post %}
               <td>Действия</td>
               {% endif %}


           </tr>




           {% for post in posts %}
           <tr>

               <td>{{ post.name|tsenzor }}</td>
               <td>{{ post.createDate|date:'M d Y' }}</td>
               <td>{{ post.description|truncatechars:20|tsenzor}}</td>
               <td>{{ post.categoryType}}</td>
               {% if post.categoryType == 'NW' and perms.simpleapp.change_post %}
                   <td> <a href="{% url 'news_update' pk=post.pk %}">Edit</a></td>
               {% elif post.categoryType == 'NW' and  perms.simpleapp.delete_post %}
                    <td><a href="{% url 'news_delete' pk=post.pk %}">Delete</a></td>
               {% elif post.categoryType == 'AR' and perms.simpleapp.change_post %}
                    <td><a href="{% url 'article_update' pk=post.pk %}">Edit</a></td>
               {% elif post.categoryType == 'AR' and perms.simpleapp.delete_post %}
                    <td><a href="{% url 'article_delete' pk=post.pk %}">Delete</a></td>
               {% endif %}
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2> Новостей нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}



